"use client";

import { useMemo, useState } from "react";
import type { GitHubSignal } from "@/lib/github-signals";

const filters = ["All", "Code", "Community", "Release"] as const;
const accents = ["bg-emerald-300", "bg-cyan-300", "bg-violet-300", "bg-amber-300", "bg-sky-300", "bg-pink-300"];

export function GitHubLiveFeed({ signals }: { signals: GitHubSignal[] }) {
  const [filter, setFilter] = useState<(typeof filters)[number]>("All");
  const [selected, setSelected] = useState(signals[0]?.project ?? "");
  const visible = useMemo(() => filter === "All" ? signals : signals.filter((signal) => signal.kind === filter), [filter, signals]);
  const focus = signals.find((signal) => signal.project === selected) ?? visible[0];

  if (!focus) return <div className="mt-10 rounded-2xl border border-dashed border-emerald-300/30 bg-emerald-300/[0.04] px-6 py-14 text-center"><p className="text-sm font-semibold text-white">GitHub signals are temporarily unavailable.</p><p className="mt-2 text-sm text-white/50">Try again shortly. This page reads GitHub&apos;s public activity API.</p></div>;

  return <div className="mt-10 grid gap-6 lg:grid-cols-[minmax(0,1fr)_21rem]"><section><div className="rounded-2xl border border-emerald-300/25 bg-emerald-300/[0.06] p-5 sm:flex sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-emerald-100">Latest activity across {signals.length} public GitHub projects</p><p className="mt-1 text-xs leading-5 text-emerald-100/55">Events refresh every five minutes through GitHub&apos;s public API.</p></div><span className="mt-4 flex items-center gap-2 text-xs font-semibold text-emerald-200 sm:mt-0"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300" /> GitHub connected</span></div><div className="mt-6 flex flex-wrap gap-2">{filters.map((item) => <button type="button" key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-xs font-semibold transition ${filter === item ? "bg-emerald-300 text-emerald-950" : "border border-white/10 bg-white/[0.03] text-white/55 hover:border-emerald-300/45 hover:text-emerald-200"}`}>{item === "All" ? "All signals" : item}</button>)}</div><div className="mt-5 space-y-3">{visible.map((signal, index) => <button type="button" key={signal.project} onClick={() => setSelected(signal.project)} className={`flex w-full items-center gap-4 rounded-xl border p-5 text-left transition ${focus.project === signal.project ? "border-emerald-300/55 bg-emerald-300/[0.08]" : "border-white/10 bg-white/[0.03] hover:border-white/25"}`}><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${accents[index % accents.length]}`} /><span className="min-w-0 flex-1"><span className="block text-sm text-white"><strong>{signal.project}</strong> <span className="text-white/55">{signal.action}</span></span><span className="mt-1 block text-xs text-white/35">{signal.kind} signal · GitHub public event</span></span><time className="shrink-0 text-xs text-white/35">{signal.time}</time></button>)}</div></section><aside className="h-fit rounded-2xl border border-white/10 bg-white/[0.03] p-6 lg:sticky lg:top-6"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-300">GitHub activity</p><h2 className="mt-5 text-xl font-semibold text-white">{focus.project}</h2><p className="mt-2 text-sm leading-6 text-white/55">This is the latest publicly available {focus.kind.toLowerCase()} event for the repository.</p><div className="mt-6 rounded-xl border border-emerald-300/20 bg-emerald-300/[0.05] p-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-emerald-300">Suggested first move</p><p className="mt-2 text-sm font-medium leading-6 text-emerald-50">Open the project and review its contribution guide, issues, and latest discussion.</p></div><a href={focus.url} target="_blank" rel="noreferrer" className="mt-6 inline-flex w-full items-center justify-center rounded-lg border border-white/15 px-4 py-2.5 text-xs font-bold text-white/75 transition hover:border-emerald-300/60 hover:text-emerald-200">Open on GitHub ↗</a></aside></div>;
}
